# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:6.5.0-jdk8-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test

build:
  stage: build
  script: gradle build
  artifacts:
    paths:
    - build/libs/nuke-client-1.0.0.jar
    expire_in: 1 week

test:
  stage: test
  script: gradle check
