# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:alpine

build:
  stage: build
  script: ./gradlew --no-daemon build
  artifacts:
    paths:
    - build/libs/nuke-client-1.0.0.jar
    expire_in: 1 week

test:
  stage: test
  script: ./gradlew --no-daemon check
